name: C++ CI

on:
  push:
    branches: ['*'] # NOTE: replace/update with appropriate branch name(s)
    tags: ['*']
  pull_request:
    branches: ['*'] # NOTE: replace/update with appropriate branch name(s)
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: false
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

env:
  BUILD_TYPE: ${{ inputs.build_type || 'Debug' }}
  EXECUTABLE_NAME: "oop"
  BIN_DIR: "bin"
  BUILD_DIR: "build"
  EXT_DIR: "ext"
  GEN_DIR: "generated"

defaults:
  run:
    shell: bash

jobs:
  cppcheck:
    name: "Cppcheck"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      CPPCHECK_VER: "2.14.2"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run cppcheck
        uses: ./.github/actions/cppcheck

  clang-tidy:
    name: "Clang-Tidy"
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      CLANG_VER: "18"
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run clang-tidy
        uses: ./.github/actions/clang-tidy

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 8
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14, windows-2022] # specify the OS platforms
        include:
          - os: ubuntu-22.04
            c: gcc-12
            cxx: g++-12
            cmake_flags: ""
          - os: macos-14
            c: clang
            cxx: clang++
            cmake_flags: ""
          - os: windows-2022
            c: gcc
            cxx: g++
            cmake_flags: ""

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set timestamp and zip name
        run: |
          echo "TIMESTAMP=$(date +%Y-%m-%d-%H-%M-%S)" >> ${GITHUB_ENV}
          echo "ZIP_NAME=$(echo "${GITHUB_REPOSITORY}_${{ env.BUILD_TYPE }}_${{ matrix.os }}_${{ matrix.cxx }}${{ matrix.asan_name }}" | sed 's|/|_|')" >> ${GITHUB_ENV}

      - name: Install dependencies
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y \
              build-essential \
              cmake \
              libopenal-dev \
              libvorbis-dev \
              libflac-dev \
              libfreetype6-dev \
              libx11-dev \
              libxrandr-dev \
              libudev-dev \
              libopencl-dev
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew update
            brew install sfml
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install mingw
            choco install cmake
            choco install openal
          fi

      - name: Configure CMake
        uses: ./.github/actions/configure-cmake
        with:
          custom_flags: ${{ matrix.cmake_flags }}
          warnings_as_errors: 'ON'

      - name: Build
        run: |
          bash ./scripts/cmake.sh build -t ${{ env.BUILD_TYPE }}

      - name: Install
        run: |
          bash ./scripts/cmake.sh install -i artifacts -t ${{ env.BUILD_TYPE }}

      - name: Move artifacts
        run: |
          mkdir ${{ env.ZIP_NAME }}
          mv artifacts/${{ env.BIN_DIR }}/* ${{ env.ZIP_NAME }}
          ls -la ${{ env.ZIP_NAME }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ZIP_NAME }}_${{ env.TIMESTAMP }}
          path: ${{ env.ZIP_NAME }}
          retention-days: 30
